language: ruby
before_install: gem update --system
before_script:
  - mysql -e 'create database thinking_sphinx;'
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/activerecord2.gemfile
  - gemfiles/activerecord3.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/activerecord2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord2.gemfile
