# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ts-resque-delta}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Gibralter"]
  s.date = %q{2010-11-20}
  s.description = %q{Manage delta indexes via Resque for Thinking Sphinx}
  s.email = %q{aaron.gibralter@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "lib/thinking_sphinx/deltas/resque_delta.rb",
     "lib/thinking_sphinx/deltas/resque_delta/delta_job.rb",
     "lib/thinking_sphinx/deltas/resque_delta/flag_as_deleted_job.rb",
     "lib/thinking_sphinx/deltas/resque_delta/tasks.rb"
  ]
  s.homepage = %q{http://github.com/agibralter/ts-resque-delta}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Thinking Sphinx - Resque Deltas}
  s.test_files = [
    "Rakefile",
     "config/redis-cucumber.conf",
     "features/resque_deltas.feature",
     "features/step_definitions",
     "features/step_definitions/common_steps.rb",
     "features/step_definitions/resque_delta_steps.rb",
     "features/support",
     "features/support/env.rb",
     "features/support/redis_test_setup.rb",
     "features/thinking_sphinx",
     "features/thinking_sphinx/database.example.yml",
     "features/thinking_sphinx/database.yml",
     "features/thinking_sphinx/db",
     "features/thinking_sphinx/db/migrations",
     "features/thinking_sphinx/db/migrations/create_delayed_betas.rb",
     "features/thinking_sphinx/models",
     "features/thinking_sphinx/models/delayed_beta.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/thinking_sphinx",
     "spec/thinking_sphinx/deltas",
     "spec/thinking_sphinx/deltas/resque_delta",
     "spec/thinking_sphinx/deltas/resque_delta/delta_job_spec.rb",
     "spec/thinking_sphinx/deltas/resque_delta/flag_as_deleted_job_spec.rb",
     "spec/thinking_sphinx/deltas/resque_delta_spec.rb",
     "tasks/distribution.rb",
     "tasks/rails.rake",
     "tasks/testing.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thinking-sphinx>, [">= 1.3.6"])
      s.add_runtime_dependency(%q<resque>, ["~> 1.10.0"])
      s.add_runtime_dependency(%q<resque-lock-timeout>, ["~> 0.2.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0.5.2"])
    else
      s.add_dependency(%q<thinking-sphinx>, [">= 1.3.6"])
      s.add_dependency(%q<resque>, ["~> 1.10.0"])
      s.add_dependency(%q<resque-lock-timeout>, ["~> 0.2.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0.5.2"])
    end
  else
    s.add_dependency(%q<thinking-sphinx>, [">= 1.3.6"])
    s.add_dependency(%q<resque>, ["~> 1.10.0"])
    s.add_dependency(%q<resque-lock-timeout>, ["~> 0.2.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0.5.2"])
  end
end

